version: "3.9"

services:
  adguardhome-ds:
    container_name: AdGuardHome-DS
    image: adguard/adguardhome:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "3000:3000/tcp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    volumes:
      - ${VOLUMEDIR}/adguardhome/work:/opt/adguardhome/work
      - ${VOLUMEDIR}/adguardhome/conf:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguardhome2.rule=Host(`adguard2.home.local`)"
      - "traefik.http.routers.adguardhome2.entrypoints=web,websecure"
      - "traefik.http.services.adguardhome2.loadbalancer.server.port=8080"
    cap_add:
      - NET_ADMIN
    restart: always