version: "3.9"

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: Syncthing
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/syncthing:/config
      - /volume1/homes/Alessandro/Books:/config/Books
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.syncthing.loadbalancer.server.port=8384
      # Old Syncthing router (insecure)
      - traefik.http.routers.syncthing-insecure.rule=Host(`syncthing.home.local`)
      - traefik.http.routers.syncthing-insecure.entrypoints=web
      - traefik.http.routers.syncthing-insecure.service=syncthing
      # Syncthing router (secure)
      - traefik.http.routers.syncthing.rule=Host(`syncthing.home.alborworld.com`)
      - traefik.http.routers.syncthing.entrypoints=websecure
      - traefik.http.routers.syncthing.service=syncthing
      - traefik.http.routers.syncthing.tls=true
      - traefik.http.routers.syncthing.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Utilities
      - homepage.name=Syncthing
      - homepage.icon=syncthing.png
      - homepage.href=https://syncthing.home.alborworld.com
      - homepage.description=File Synchronization
      - homepage.siteMonitor=https://syncthing.home.alborworld.com
    restart: unless-stopped