version: "3.9"

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: Syncthing
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/syncthing:/config
      - /volume1/homes/Alessandro/Books:/config/Books
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.home.local`)"
      - "traefik.http.routers.syncthing.entrypoints=web,websecure"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
    restart: unless-stopped