---
http:
  routers:
    pbs:
      rule: "Host(`pbs.home.alborworld.com`)"
      service: pbs
      entryPoints:
        - websecure
      middlewares:
        - pbs-headers
      tls:
        certResolver: cloudflare

  middlewares:
    pbs-headers:
      headers:
        customRequestHeaders:
          Authorization: ""
          Cookie: ""

  services:
    pbs:
      loadBalancer:
        servers:
          - url: "https://pbs.home:8007"
        passHostHeader: true
        serversTransport: insecureTransport

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
