---
http:
  routers:
    pbs:
      rule: "Host(`pbs.home.alborworld.com`)"
      service: pbs
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

  services:
    pbs:
      loadBalancer:
        servers:
          - url: "https://pbs.home:8007"
        passHostHeader: true
        serversTransport: insecureTransport

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
