---
http:
  routers:
    proxmox:
      rule: "Host(`proxmox.home.local`)"
      service: proxmox
      entryPoints:
        - web
        - websecure
      middlewares:
        - proxmox-headers

  middlewares:
    proxmox-headers:
      headers:
        customRequestHeaders:
          Authorization: ""
          Cookie: ""

  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://nuc.local:8006"
        passHostHeader: true
        serversTransport: insecureTransport

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
