---
http:
  routers:
    proxmox:
      rule: "Host(`proxmox.home.alborworld.com`)"
      service: proxmox
      entryPoints:
        - websecure
      middlewares:
        - proxmox-headers
      tls:
        certResolver: cloudflare

  middlewares:
    proxmox-headers:
      headers:
        customRequestHeaders:
          Authorization: ""
          Cookie: ""

  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://nuc.home:8006"
        passHostHeader: true
        serversTransport: insecureTransport

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
