---
http:
  routers:
    pve:
      rule: "Host(`pve.home.alborworld.com`)"
      service: pve
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

  services:
    pve:
      loadBalancer:
        servers:
          - url: "https://pve.home:8006"
        passHostHeader: true
        serversTransport: insecureTransport

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
