---
http:
  routers:
    pve:
      rule: "Host(`pve.home.alborworld.com`)"
      service: pve
      entryPoints:
        - websecure
      middlewares:
        - pve-headers
      tls:
        certResolver: cloudflare

  middlewares:
    pve-headers:
      headers:
        customRequestHeaders:
          Authorization: ""
          Cookie: ""

  services:
    pve:
      loadBalancer:
        servers:
          - url: "https://nuc.home:8006"
        passHostHeader: true
        serversTransport: insecureTransport

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
