services:
  homarr:
    container_name: Homarr
    image: ghcr.io/ajnart/homarr:latest
    ports:
      - 7575:7575
    volumes:
      - ${CONFIGDIR}/homarr:/app/data/configs
      - ${CONFIGDIR}/homarr/data:/data
      - ${CONFIGDIR}/homarr/icons:/app/public/icons
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.homarr.loadbalancer.server.port=7575
      - traefik.http.routers.homarr.rule=Host(`homarr.${LOCAL_DOMAIN}`)
      - traefik.http.routers.homarr.entrypoints=websecure
      - traefik.http.routers.homarr.service=homarr
      - traefik.http.routers.homarr.tls=true
      - traefik.http.routers.homarr.tls.certresolver=cloudflare
    restart: unless-stopped