services:
  homarr:
    container_name: Homarr
    image: ghcr.io/ajnart/homarr:latest
    ports:
      - 7575:7575
    volumes:
      - ${CONFIGDIR}/homarr:/app/data/configs
      - ${CONFIGDIR}/homarr/data:/data
      - ${CONFIGDIR}/homarr/icons:/app/public/icons
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.rule=Host(`homarr.home.local`)"
      - "traefik.http.routers.homarr.entrypoints=web,websecure"
    restart: unless-stopped