services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: Dozzle
    environment:
      - TZ=Europe/Amsterdam
      - DOZZLE_HOSTNAME=dockerhost
      - DOZZLE_REMOTE_AGENT=10.0.4.94:7007,10.0.4.111:7007
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9999:8080"
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.dozzle.loadbalancer.server.port=9999
      - traefik.http.routers.dozzle.rule=Host(`dozzle.${LOCAL_DOMAIN}`)
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.routers.dozzle.service=dozzle
      - traefik.http.routers.dozzle.tls=true
      - traefik.http.routers.dozzle.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Monitoring & Health
      - homepage.name=Dozzle
      - homepage.icon=dozzle.png
      - homepage.href=https://dozzle.${LOCAL_DOMAIN}
      - homepage.description=Container Log Viewer
      - homepage.siteMonitor=https://dozzle.${LOCAL_DOMAIN}
    restart: always
