services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:release-4.6.0
    container_name: qBittorrent
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/qbittorrent:/config
      - ${MEDIADIR}/downloads:/app/qBittorrent/downloads
    network_mode: "service:gluetun"
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.qbittorrent.loadbalancer.server.port=7091
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${LOCAL_DOMAIN}`)
      - traefik.http.routers.qbittorrent.entrypoints=websecure
      - traefik.http.routers.qbittorrent.service=qbittorrent
      - traefik.http.routers.qbittorrent.tls=true
      - traefik.http.routers.qbittorrent.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Download Clients
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=https://qbittorrent.${LOCAL_DOMAIN}
      - homepage.description=Torrent Downloader
      - homepage.siteMonitor=https://qbittorrent.${LOCAL_DOMAIN}
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=https://qbittorrent.${LOCAL_DOMAIN}
      - homepage.widget.username=${QBITTORRENT_USERNAME}
      - homepage.widget.password=${QBITTORRENT_PASSWORD}
      - homepage.widget.enableLeechProgress=true
    restart: always