server:
  address: tcp://0.0.0.0:9091/

log:
  level: debug

theme: auto

#totp:
#  issuer: authelia.com

identity_validation:
  reset_password:
#    jwt_secret: ${AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET}

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/secrets/users_database.yml
    password:
      algorithm: argon2
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    - domain: '*.{{ mustEnv "LOCAL_DOMAIN" }}'
      policy: one_factor

session:
#  secret: ${AUTHELIA_SESSION_SECRET}
  cookies:
    - name: authelia_session
      domain: '{{ mustEnv "LOCAL_DOMAIN" }}'
      authelia_url: 'https://auth.{{ mustEnv "LOCAL_DOMAIN" }}'
      expiration: 1h
      inactivity: 5m
      default_redirection_url: 'https://homepage.{{ mustEnv "LOCAL_DOMAIN" }}'

  # Needed for HA
  #
  # redis:
  #   host: redis
  #   port: 6379
  #   # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
  #   # password: authelia

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
#  encryption_key: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
  local:
    path: /config/data/db.sqlite3

notifier:
  # smtp:
  #   username: test
  #   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   password: password
  #   host: mail.example.com
  #   port: 25
  #   sender: admin@example.com
  filesystem:
    filename: /config/data/notification.txt
