services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: Tdarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Amsterdam
    ports:
      - "8265:8265" # Web UI
      - "8266:8266" # Server port (for nodes to connect)
    volumes:
      - ${VOLUMEDIR}/tdarr/configs:/app/configs
      - ${VOLUMEDIR}/tdarr/logs:/app/logs
      - ${VOLUMEDIR}/tdarr/transcode:/transcode
      - ${MEDIADIR}:/media # shared with Plex
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.tdarr.loadbalancer.server.port=8265
      - traefik.http.routers.tdarr.rule=Host(`tdarr.${LOCAL_DOMAIN}`)
      - traefik.http.routers.tdarr.entrypoints=websecure
      - traefik.http.routers.tdarr.service=tdarr
      - traefik.http.routers.tdarr.tls=true
      - traefik.http.routers.tdarr.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Media Automation
      - homepage.name=Tdarr
      - homepage.icon=tdarr.png
      - homepage.href=https://tdarr.${LOCAL_DOMAIN}
      - homepage.description=Media Transcoding
      - homepage.siteMonitor=https://tdarr.${LOCAL_DOMAIN}
      - homepage.widget.type=tdarr
      - homepage.widget.url=https://tdarr.${LOCAL_DOMAIN}
    restart: unless-stopped
