services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: Tautulli
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Amsterdam
    ports:
      - "8181:8181"
    depends_on:
      plex:
        condition: service_started
    volumes:
      - ${VOLUMEDIR}/tautulli:/config
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.tautulli.loadbalancer.server.port=8181
      # Old Tautulli router (insecure)
      - traefik.http.routers.tautulli-insecure.rule=Host(`tautulli.home.local`)
      - traefik.http.routers.tautulli-insecure.entrypoints=web
      - traefik.http.routers.tautulli-insecure.service=tautulli
      # Tautulli router (secure)
      - traefik.http.routers.tautulli.rule=Host(`tautulli.${LOCAL_DOMAIN}`)
      - traefik.http.routers.tautulli.entrypoints=websecure
      - traefik.http.routers.tautulli.service=tautulli
      - traefik.http.routers.tautulli.tls=true
      - traefik.http.routers.tautulli.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Plex
      - homepage.name=Tautulli
      - homepage.icon=tautulli.png
      - homepage.href=https://tautulli.${LOCAL_DOMAIN}
      - homepage.description=Plex Statistics
      # For some reason the siteMonitor for Tautulli wants http and not https
      #- homepage.siteMonitor=https://tautulli.${LOCAL_DOMAIN}
      - homepage.siteMonitor=http://tautulli.home.local
      - homepage.widget.type=tautulli
      - homepage.widget.url=https://tautulli.${LOCAL_DOMAIN}
      - homepage.widget.key=${TAUTULLI_API_KEY}
      - homepage.widget.enableUser=true
      - homepage.widget.showEpisodeNumber=true
      - homepage.widget.expandOneStreamToTwoRows=false
    restart: always