# NordVPN WireGuard Configuration
# Generated by OpenTofu - do not edit manually

[Interface]
PrivateKey = ${private_key}
Address = 10.5.0.2/32
DNS = 103.86.96.100, 103.86.99.100

[Peer]
PublicKey = ${public_key}
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = ${endpoint}
PersistentKeepalive = 25