version: "3.9"

services:
  adguardhome-replica:
    container_name: AdGuardHomeReplica
    image: adguard/adguardhome:latest
    network_mode: host
    volumes:
      - ${VOLUMEDIR}/adguardhome-replica/work:/opt/adguardhome/work
      - ${VOLUMEDIR}/adguardhome-replica/conf:/opt/adguardhome/conf
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.adguardhome-replica.loadbalancer.server.port=8081
      - traefik.http.routers.adguardhome-replica.rule=Host(`adguard-replica.${LOCAL_DOMAIN}`)
      - traefik.http.routers.adguardhome-replica.entrypoints=websecure
      - traefik.http.routers.adguardhome-replica.service=adguardhome-replica
      - traefik.http.routers.adguardhome-replica.tls=true
      - traefik.http.routers.adguardhome-replica.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Networking & Security
      - homepage.name=AdGuard Home Replica
      - homepage.icon=adguard-home.png
      - homepage.href=https://adguard-replica.${LOCAL_DOMAIN}
      - homepage.siteMonitor=https://adguard-replica.${LOCAL_DOMAIN}
      - homepage.description=DNS Ad-blocker
      - homepage.widget.type=adguard
      - homepage.widget.url=https://adguard-replica.${LOCAL_DOMAIN}
      - homepage.widget.username=${ADGUARD_SYNC_REPLICA_USERNAME}
      - homepage.widget.password=${ADGUARD_SYNC_REPLICA_PASSWORD}
    depends_on:
      - unbound-replica
    cap_add:
      - NET_ADMIN
    restart: always
