services:
  homeassistant:
    container_name: HomeAssistant
    image: ghcr.io/home-assistant/home-assistant
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.homeassistant.loadbalancer.server.url=http://172.17.0.1:8123
      - traefik.http.routers.homeassistant.rule=Host(`homeassistant.${LOCAL_DOMAIN}`)
      - traefik.http.routers.homeassistant.entrypoints=websecure
      - traefik.http.routers.homeassistant.service=homeassistant
      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.homeassistant.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Home & Utilities
      - homepage.name=Home Assistant
      - homepage.icon=home-assistant.png
      - homepage.href=https://homeassistant.${LOCAL_DOMAIN}
      - homepage.siteMonitor=https://homeassistant.${LOCAL_DOMAIN}
      - homepage.description=Home Automation
    restart: unless-stopped