services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: NZBget
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Amsterdam
      - NZBGET_USER=${NZBGET_USER}
      - NZBGET_PASS=${NZBGET_PASS}
    volumes:
      - ${VOLUMEDIR}/nzbget:/config
      - ${MEDIADIR}/downloads:/downloads
    network_mode: "service:gluetun"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nzbget.loadbalancer.server.port=6789"
      # Old NZBGet router (insecure)
      - "traefik.http.routers.nzbget-insecure.rule=Host(`nzbget.home.local`)"
      - "traefik.http.routers.nzbget-insecure.entrypoints=web"
      - "traefik.http.routers.nzbget-insecure.service=nzbget"
      # NZBGet router (secure)
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.home.alborworld.com`)"
      - "traefik.http.routers.nzbget.entrypoints=websecure"
      - "traefik.http.routers.nzbget.service=nzbget"
      - "traefik.http.routers.nzbget.tls=true"
      - "traefik.http.routers.nzbget.tls.certresolver=cloudflare"
    restart: always