---
http:
  routers:
    diskstation-backup:
      rule: "Host(`diskstation-backup.home.alborworld.com`)"
      service: diskstation-backup
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

  services:
    diskstation-backup:
      loadBalancer:
        servers:
          - url: "https://diskstation-backup.home:5001"
        passHostHeader: true
        serversTransport: insecureTransport

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
