---
http:
  routers:
    diskstation:
      rule: "Host(`diskstation.home.alborworld.com`)"
      service: diskstation
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

  services:
    diskstation:
      loadBalancer:
        servers:
          - url: "https://diskstation.home:5001"
        passHostHeader: true
        serversTransport: insecureTransport

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
