services:
  adguardhome:
    image: adguard/adguardhome
    container_name: AdGuardHome
    network_mode: host
    volumes:
      - ${VOLUMEDIR}/adguardhome/work:/opt/adguardhome/work
      - ${VOLUMEDIR}/adguardhome/conf:/opt/adguardhome/conf
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.adguardhome.loadbalancer.server.port=8081
      - traefik.http.routers.adguardhome.rule=Host(`adguard.${LOCAL_DOMAIN}`)
      - traefik.http.routers.adguardhome.entrypoints=websecure
      - traefik.http.routers.adguardhome.service=adguardhome
      - traefik.http.routers.adguardhome.tls=true
      - traefik.http.routers.adguardhome.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Networking & Security
      - homepage.name=Adguard Home
      - homepage.icon=adguard-home.png
      - homepage.href=https://adguard.${LOCAL_DOMAIN}
      - homepage.siteMonitor=https://adguard.${LOCAL_DOMAIN}
      - homepage.description=DNS Ad-blocker
      - homepage.widget.type=adguard
      - homepage.widget.url=https://adguard.${LOCAL_DOMAIN}
      - homepage.widget.username=${ADGUARD_HOME_USERNAME}
      - homepage.widget.password=${ADGUARD_HOME_PASSWORD}
    cap_add:
      - NET_ADMIN
    restart: always
