services:
  traefik:
    image: traefik:v3.4
    container_name: Traefik
    user: "${UID}:${GID}"
    group_add:
      - ${DGID}
    ports:
      - "80:80"
      - "443:443"
      - "9090:8080"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ${VOLUMEDIR}/traefik/certs/:/var/traefik/certs/:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${LOCAL_DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
      # Add basic auth middleware for the admin dashboard
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_AUTH_USERS}"
      # - "traefik.http.routers.traefik.middlewares=traefik-auth"
      # HOMEPAGE
      - homepage.group=Core Infrastructure
      - homepage.name=Traefik
      - homepage.icon=traefik.png
      - homepage.href=https://traefik.${LOCAL_DOMAIN}
      - homepage.description=Reverse Proxy
      - homepage.siteMonitor=https://traefik.${LOCAL_DOMAIN}
      - homepage.widget.type=traefik
      - homepage.widget.url=https://traefik.${LOCAL_DOMAIN}
    restart: unless-stopped
