services:
  grafana:
    image: grafana/grafana
    container_name: Grafana
    volumes:
      - ${VOLUMEDIR}/grafana:/var/lib/grafana
    ports:
      - 3001:3000
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.node=dockerhost
      - traefik.http.services.grafana.loadbalancer.server.port=3001
      # Old Grafana router (insecure)
      - traefik.http.routers.grafana-insecure.rule=Host(`grafana.home.local`)
      - traefik.http.routers.grafana-insecure.entrypoints=web
      - traefik.http.routers.grafana-insecure.service=grafana
      # Grafana router (secure)
      - traefik.http.routers.grafana.rule=Host(`grafana.home.alborworld.com`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.service=grafana
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Monitoring
      - homepage.name=Grafana
      - homepage.icon=grafana.png
      - homepage.href=https://grafana.home.alborworld.com
      - homepage.description=Metrics Dashboards
      - homepage.siteMonitor=https://grafana.home.alborworld.com
    restart: unless-stopped