version: "3.9"

services:
  adguardhome-replica:
    container_name: AdGuardHomeReplica
    image: adguard/adguardhome:latest
    network_mode: host
    volumes:
      - ${VOLUMEDIR}/adguardhome-replica/work:/opt/adguardhome/work
      - ${VOLUMEDIR}/adguardhome-replica/conf:/opt/adguardhome/conf
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.adguardhome-replica.loadbalancer.server.port=8081
      - traefik.http.routers.adguardhome-replica.rule=Host(`adguard-replica.${LOCAL_DOMAIN}`)
      - traefik.http.routers.adguardhome-replica.entrypoints=websecure
      - traefik.http.routers.adguardhome-replica.service=adguardhome-replica
      - traefik.http.routers.adguardhome-replica.tls=true
      - traefik.http.routers.adguardhome-replica.tls.certresolver=cloudflare
    cap_add:
      - NET_ADMIN
    restart: always
