services:
  postfix:
    image: boky/postfix
    container_name: PostfixRelay
    environment:
      RELAYHOST: ${POSTFIX_RELAYHOST}
      RELAYHOST_USERNAME: ${POSTFIX_RELAYHOST_USERNAME}
      RELAYHOST_PASSWORD: ${POSTFIX_RELAYHOST_PASSWORD}
      POSTFIX_myhostname: 'smtp-relay.${LOCAL_DOMAIN}'
      DOMAINNAME: '${LOCAL_DOMAIN}'
      ALLOWED_SENDER_DOMAINS: ${POSTFIX_ALLOWED_SENDER_DOMAINS}
      POSTFIX_mynetworks: ${POSTFIX_mynetworks}
      LOGLEVEL: 'info'
      POSTFIX_smtp_tls_security_level: 'no'
      POSTFIX_smtpd_tls_security_level: 'no'
      POSTFIX_smtpd_use_tls: 'no'
      POSTFIX_smtpd_tls_wrappermode: 'no'
    labels:
      - traefik.enable=true
      # Submission (port 587, client auth)
      - traefik.tcp.routers.postfix-sub.entrypoints=submission
      - traefik.tcp.routers.postfix-sub.rule=HostSNI(`smtp.${LOCAL_DOMAIN}`)
      - traefik.tcp.routers.postfix-sub.service=postfix-sub
      - traefik.tcp.services.postfix-sub.loadbalancer.server.port=587
      # Terminate TLS in Traefik:
      - traefik.tcp.routers.postfix-sub.tls=true
      - traefik.tcp.routers.postfix-sub.tls.certresolver=cloudflare
    restart: unless-stopped

