services:
  github-runner-rp:
    image: myoung34/github-runner:latest
    container_name: GitHubRunner-RP
    environment:
      REPO_URL: ${GITHUB_RUNNER_REPO_URL}
      ACCESS_TOKEN: ${GITHUB_RUNNER_ACCESS_TOKEN}
      RUNNER_NAME: "homelab-raspberrypi5-runner"
      LABELS: "docker,homelab,raspberrypi5"
      # Uncomment below for Org-wide runner
      # ORG_RUNNER: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker-in-Docker access
      - ${VOLUMEDIR}/github-runner-rp:/runner/_work  # Runner working directory
      - /home/pi/homelab:/homelab  # Access to homelab repo
    restart: unless-stopped
