services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: Prowlarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/prowlarr:/config
    network_mode: "service:gluetun"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.home.local`)"
      - "traefik.http.routers.prowlarr.entrypoints=web,websecure"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    restart: always