services:
  beszel:
    image: henrygd/beszel:latest
    container_name: Beszel
    volumes:
      - ${VOLUMEDIR}/beszel/data:/beszel_data
      - ${VOLUMEDIR}/beszel/socket:/beszel_socket
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`beszel.${LOCAL_DOMAIN}`)
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.routers.beszel.tls=true
      - traefik.http.routers.beszel.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Monitoring
      - homepage.name=Beszel
      - homepage.icon=beszel.png
      - homepage.href=https://beszel.${LOCAL_DOMAIN}
      - homepage.siteMonitor=https://beszel.${LOCAL_DOMAIN}
      - homepage.description=Server Monitoring Platform
    restart: unless-stopped