services:
  nextcloud:
    image: nextcloud:latest
    container_name: NextCloud
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=nextcloud-db
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/nextcloud/html:/var/www/html
      - /mnt/Alessandro:/mnt/Alessandro
      - /mnt/CorsiOnline:/mnt/CorsiOnline
    devices:
      - /dev/dri:/dev/dri
    labels:
      - traefik.enable=true
      - traefik.http.services.nextcloud.loadbalancer.server.port=8081
      # Old Nextcloud router (insecure)
      - traefik.http.routers.nextcloud-insecure.rule=Host(`nextcloud.home.local`)
      - traefik.http.routers.nextcloud-insecure.entrypoints=web
      - traefik.http.routers.nextcloud-insecure.service=nextcloud
      # Nextcloud router for shamanism-nature.com (no TLS, handled by Cloudflare Tunnel)
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${NEXTCLOUD_DOMAIN}`)
      - traefik.http.routers.nextcloud.entrypoints=web
      - traefik.http.routers.nextcloud.service=nextcloud
    depends_on:
      - nextcloud-db
    networks:
      - nextcloud_network

  nextcloud-db:
    image: mariadb:11.4
    container_name: NextCloudDb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/nextcloud/database:/var/lib/mysql
    networks:
      - nextcloud_network

  redis:
    image: redis:alpine
    command: redis-server --protected-mode no
    container_name: NextCloudRedis
    restart: unless-stopped
    networks:
      - nextcloud_network

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: OnlyOffice
    restart: unless-stopped
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLY_OFFICE_JWT_SECRET}
    ports:
      - 9980:80
    volumes:
      - ${VOLUMEDIR}/nextcloud/logs/onlyoffice:/var/log/onlyoffice
    labels:
      - traefik.enable=true
      - traefik.http.services.onlyoffice.loadbalancer.server.port=9980
      # OnlyOffice router for shamanism-nature.com (no TLS, handled by Cloudflare Tunnel)
      - traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.${NEXTCLOUD_DOMAIN}`)
      - traefik.http.routers.onlyoffice.entrypoints=web
      - traefik.http.routers.onlyoffice.service=onlyoffice
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
    driver: bridge
