services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: Radarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/radarr:/config
      - ${MEDIADIR}/movies:/movies
      - ${MEDIADIR}/downloads:/app/qBittorrent/downloads
      - ${MEDIADIR}/downloads/complete/Movies:/downloads/complete/Movies
    network_mode: "service:gluetun"
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      # Old Radarr router (insecure)
      - traefik.http.routers.radarr-insecure.rule=Host(`radarr.home.local`)
      - traefik.http.routers.radarr-insecure.entrypoints=web
      - traefik.http.routers.radarr-insecure.service=radarr
      # Radarr router (secure)
      - traefik.http.routers.radarr.rule=Host(`radarr.home.alborworld.com`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.service=radarr
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Media
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=https://radarr.home.alborworld.com
      - homepage.description=Movies Automation
      - homepage.siteMonitor=https://radarr.home.alborworld.com
      - homepage.widget.type=radarr
      - homepage.widget.url=https://radarr.home.alborworld.com
      - homepage.widget.key=${RADARR_API_KEY}
    restart: always