services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: Radarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/radarr:/config
      - ${MEDIADIR}/movies:/movies
      - ${MEDIADIR}/downloads:/app/qBittorrent/downloads
      - ${MEDIADIR}/downloads/complete/Movies:/downloads/complete/Movies
    network_mode: "service:gluetun"
    labels:
      - traefik.enable=true
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      # Old Radarr router (insecure)
      - traefik.http.routers.radarr-insecure.rule=Host(`radarr.home.local`)
      - traefik.http.routers.radarr-insecure.entrypoints=web
      - traefik.http.routers.radarr-insecure.service=radarr
      # Radarr router (secure)
      - traefik.http.routers.radarr.rule=Host(`radarr.home.alborworld.com`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.service=radarr
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=cloudflare
    restart: always