version: "3.9"

services:
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: AdGuardHomeSync
    ports:
      - 8082:8080
    environment:
      - ORIGIN_URL=http://10.0.4.94:8080
      - ORIGIN_USERNAME=${ADGUARD_ORIGIN_USERNAME}
      - ORIGIN_PASSWORD=${ADGUARD_ORIGIN_PASSWORD}
      - REPLICA_URL=http://AdGuardHome-DS:80
      - REPLICA_USERNAME=${ADGUARD_REPLICA_USERNAME}
      - REPLICA_PASSWORD=${ADGUARD_REPLICA_PASSWORD}
      - RUNONSTART=true
      - CRON=0 */2 * * *
      - FEATURE_DSN_ACCESS_LIST=true
      - FEATURE_DNS_SERVER_CONFIG=true
      - FEATURE_DNS_REWRITES=true
      - FEATURE_FILTERS=true
      - FEATURE_STATS_CONFIG=true
      - FEATURE_CLIENT_SETTINGS=true
      - FEATURE_SERVICES=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.adguardhome-sync.loadbalancer.server.port=8082"
      # Old AdGuardHome Sync router (insecure)
      - "traefik.http.routers.adguardhome-sync-insecure.rule=Host(`adguardhome-sync.home.local`)"
      - "traefik.http.routers.adguardhome-sync-insecure.entrypoints=web"
      - "traefik.http.routers.adguardhome-sync-insecure.service=adguardhome-sync"
      # AdGuardHome Sync router (secure)
      - "traefik.http.routers.adguardhome-sync.rule=Host(`adguardhome-sync.home.alborworld.com`)"
      - "traefik.http.routers.adguardhome-sync.entrypoints=websecure"
      - "traefik.http.routers.adguardhome-sync.service=adguardhome-sync"
      - "traefik.http.routers.adguardhome-sync.tls=true"
      - "traefik.http.routers.adguardhome-sync.tls.certresolver=cloudflare"
    depends_on:
      - adguardhome-ds
    restart: always