services:
  onlyoffice-document-server:
    image: onlyoffice/documentserver:latest
    container_name: OnlyOffice
    ports:
      - "8083:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_DOCUMENT_SERVER_JWT_SECRET}
    restart: always