services:
  wud-proxy-dh:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: WudProxy-DH
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - POST=1
    ports:
      - 2376:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - wud.watch=false
    restart: unless-stopped
