services:
  dozzle-agent-ds:
    image: amir20/dozzle:latest
    container_name: DozzleAgent-DS
    command: agent
    environment:
      - DOZZLE_HOSTNAME=diskstation
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "7007:7007"
    restart: always
