services:
  adguardhome:
    image: adguard/adguardhome
    container_name: AdGuardHome
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"        # For DHCP if needed
      - "8080:80/tcp"      # HTTP web,websecure interface
      - "8443:443/tcp"     # HTTPS web,websecure interface
    volumes:
      - ${VOLUMEDIR}/adguardhome/work:/opt/adguardhome/work
      - ${VOLUMEDIR}/adguardhome/conf:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguardhome.rule=Host(`adguard.home.local`)"
      - "traefik.http.routers.adguardhome.entrypoints=web,websecure"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=80" 
    cap_add:
      - NET_ADMIN
    restart: always