services:
  adguardhome:
    image: adguard/adguardhome
    container_name: AdGuardHome
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"        # For DHCP if needed
      - "8080:80/tcp"      # HTTP web,websecure interface
      - "8443:443/tcp"     # HTTPS web,websecure interface
    volumes:
      - ${VOLUMEDIR}/adguardhome/work:/opt/adguardhome/work
      - ${VOLUMEDIR}/adguardhome/conf:/opt/adguardhome/conf
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.adguardhome.loadbalancer.server.port=80
      # Old AdGuardHome router (insecure)
      - traefik.http.routers.adguardhome-insecure.rule=Host(`adguard.home.local`)
      - traefik.http.routers.adguardhome-insecure.entrypoints=web
      - traefik.http.routers.adguardhome-insecure.service=adguardhome
      # AdGuardHome router (secure)
      - traefik.http.routers.adguardhome.rule=Host(`adguard.home.alborworld.com`)
      - traefik.http.routers.adguardhome.entrypoints=websecure
      - traefik.http.routers.adguardhome.service=adguardhome
      - traefik.http.routers.adguardhome.tls=true
      - traefik.http.routers.adguardhome.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Networking
      - homepage.name=Adguard Home
      - homepage.icon=adguard-home.png
      - homepage.href=https://adguard.home.alborworld.com
      - homepage.siteMonitor=https://adguard.home.alborworld.com
      - homepage.description=Ad blocker and DNS filtering
      - homepage.widget.type=adguard
      - homepage.widget.url=https://adguard.home.alborworld.com
      - homepage.widget.username=${ADGUARD_HOME_USERNAME}
      - homepage.widget.password=${ADGUARD_HOME_PASSWORD}
    cap_add:
      - NET_ADMIN
    restart: always