services:
  vault:
    image: vault:latest
    container_name: Vault
    ports:
      - "8200:8200"
    volumes:
      - ${VOLUMEDIR}/vault/file:/vault/file:rw
      - ${VOLUMEDIR}/vault/config:/vault/config:rw
      - ${VOLUMEDIR}/vault/policies:/vault/policies:rw
      - ${VOLUMEDIR}/vault/data:/vault/data:rw
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.vault.loadbalancer.server.port=8200
      - traefik.http.routers.vault.rule=Host(`vault.${INTERNAL_DOMAIN}`)
      - traefik.http.routers.vault.entrypoints=websecure
      - traefik.http.routers.vault.service=vault
      - traefik.http.routers.vault.tls=true
      - traefik.http.routers.vault.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Infrastructure
      - homepage.name=Vault
      - homepage.icon=vault.png
      - homepage.href=https://vault.${INTERNAL_DOMAIN}
      - homepage.description=Secrets Management
      - homepage.siteMonitor=https://vault.${INTERNAL_DOMAIN}/v1/sys/health
    restart: unless-stopped
