---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

my-docker:
  host: dockerproxy-rp
  port: 2375

dockerhost:
  host: 10.0.4.53
  port: 2375
#  host: https://dockerproxy.dockerhost.{{HOMEPAGE_VAR_LOCAL_DOMAIN}}
#  port: 443
#  protocol: https

diskstation:
  host: 10.0.4.111
  port: 2375
#  host: https://dockerproxy.diskstation.{{HOMEPAGE_VAR_LOCAL_DOMAIN}}
#  port: 443
#  protocol: https
