---
# For configuration options and examples, please see:
# https://ge.home.localpage.dev/configs/services/

- Infrastructure:
    - Portainer:
        icon: portainer.png
#        href: http://portainer.home.local
        href: https://portainer.home.alborworld.com
        description: Container Management
#        siteMonitor: http://portainer.home.local
        siteMonitor: https://portainer.home.alborworld.com
    - Proxmox:
        icon: proxmox.png
#        href: https://proxmox.home.alborworld.com
        href: https://nuc.home:8006
        description: NUC – VM & Container Management
#        siteMonitor: https://proxmox.home.alborworld.com
        siteMonitor: https://nuc.home:8006
    - Proxmox Backup Server:
        icon: proxmox.png
#        href: https://pbs.home.alborworld.com
        href: https://pbs.home:8007
        description: Backup Server for VMs & Containers
#        siteMonitor: https://pbs.home.alborworld.com
        siteMonitor: https://pbs.home:8007
    - Traefik:
        icon: traefik.png
#        href: http://traefik.home.local
        href: https://traefik.home.alborworld.com
        description: Reverse Proxy
#        siteMonitor: http://traefik.home.local
        siteMonitor: https://traefik.home.alborworld.com
        widget:
          type: traefik
#          url: http://traefik.home.local
          url: https://traefik.home.alborworld.com
    - Vault:
        icon: vault.png
#        href: http://vault.home.local
        href: https://vault.home.alborworld.com
        description: Secrets Management
#        siteMonitor: http://vault.home.local/v1/sys/health
        siteMonitor: https://vault.home.alborworld.com/v1/sys/health

- Networking:
    - AdGuard Home:
        icon: adguard-home.png
#        href: http://adguard.home.local
        href: https://adguard.home.alborworld.com
        description: Ad blocker and DNS filtering
#        siteMonitor: http://adguard.home.local
        siteMonitor: https://adguard.home.alborworld.com
        widget:
          type: adguard
#          url: http://adguard.home.local
          url: https://adguard.home.alborworld.com
          username: {{HOMEPAGE_VAR_ADGUARD_HOME_USERNAME}}
          password: {{HOMEPAGE_VAR_ADGUARD_HOME_PASSWORD}}
    - UpSnap:
        icon: upsnap.png
#        href: http://upsnap.home.local
        href: https://upsnap.home.alborworld.com
        description: Wake on lan web app
#        siteMonitor: http://upsnap.home.local
        siteMonitor: https://upsnap.home.alborworld.com

- Network Devices:
    - Synology DiskStation:
        icon: synology.png
#        href: https://alborworld-diskstation.synology.me
#        href: http://diskstation.home.local
#        href: https://diskstation.home.alborworld.com
        href: http://diskstation.home:5000
        description: Synology DS218+ NAS
#        siteMonitor: https://alborworld-diskstation.synology.me
#        siteMonitor: http://diskstation.home.local
#        siteMonitor: https://diskstation.home.alborworld.com
        siteMonitor: http://diskstation.home:5000
    - Synology DiskStation Backup:
        icon: synology.png
#        href: https://alborworld-diskstation.synology.me
#        href: http://10.0.4.34:5000/
#        href: http://diskstation-backup.home.local
#        href: https://diskstation-backup.home.alborworld.com
        href: http://diskstation-backup.home:5000
        description: Synology DS214 NAS
#        siteMonitor: https://alborworld-diskstation-backup.synology.me
#        siteMonitor: http://10.0.4.34:5000/
#        siteMonitor: http://diskstation-backup.home.local
#        siteMonitor: https://diskstation-backup.home.alborworld.com
        siteMonitor: http:diskstation-backup.home:5000
    - Synology Router:
        icon: synology.png
        href: https://alborworld-router.synology.me:8001
        description: Synology RT2600ac Router
        siteMonitor: https://alborworld-router.synology.me

- Monitoring:
    - Beszel:
        icon: beszel.png
#        href: http://beszel.home.local
        href: https://beszel.home.alborworld.com
        description: Server Monitoring Platform
#        siteMonitor: http://beszel.home.local
        siteMonitor: https://beszel.home.alborworld.com
    - Grafana:
        icon: grafana.png
#        href: http://grafana.home.local
        href: https://grafana.home.alborworld.com
        description: Metrics Dashboards
#        siteMonitor: http://grafana.home.local
        siteMonitor: https://grafana.home.alborworld.com
    - Prometheus:
        icon: prometheus.png
#        href: http://prometheus.home.local
        href: https://prometheus.home.alborworld.com
        description: Time-Series Metrics Collector
#        siteMonitor: http://prometheus.home.local/metrics
        siteMonitor: https://prometheus.home.alborworld.com/metrics
    - Speedtest Tracker:
        icon: speedtest-tracker.png
#        href: http://speedtest.home.local
        href: https://speedtest.home.alborworld.com
        description: Internet Speed History
#        siteMonitor: http://speedtest.home.local
        siteMonitor: https://speedtest.home.alborworld.com
        widget:
          type: speedtest
#          url: http://speedtest.home.local
          url: https://speedtest.home.alborworld.com
          version: 1
          bitratePrecision: 3
    - Uptime Kuma:
        icon: uptime-kuma.png
#        href: http://uptimekuma.home.local
        href: https://uptimekuma.home.alborworld.com
        description: Service Uptime Monitor
#        siteMonitor: http://uptimekuma.home.local
        siteMonitor: https://uptimekuma.home.alborworld.com
        widget:
          type: uptimekuma
#          url: http://uptimekuma.home.local
          url: https://uptimekuma.home.alborworld.com
          slug: shamanism

- Download Clients:
    - NZBGet:
        icon: nzbget.png
#        href: http://nzbget.home.local
        href: https://nzbget.home.alborworld.com
        description: Usenet Downloader
#        siteMonitor: http://nzbget.home.local
        siteMonitor: https://nzbget.home.alborworld.com
    - qBittorrent:
        icon: qbittorrent.png
#        href: http://qbittorrent.home.local
        href: https://qbittorrent.home.alborworld.com
        description: Torrent Downloader
#        siteMonitor: http://qbittorrent.home.local
        siteMonitor: https://qbittorrent.home.alborworld.com
        widget:
          type: qbittorrent
#          url: http://qbittorrent.home.local
          url: https://qbittorrent.home.alborworld.com
          username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
          password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
          enableLeechProgress: true

- Plex:
    - Plex:
        icon: plex.png
#        href: http://plex.home.local
        href: https://plex.home.alborworld.com
        description: Plex Media Server
#        siteMonitor: http://plex.home.local
        siteMonitor: https://plex.home.alborworld.com
        widget:
          type: plex
#          url: http://plex.home.local
          url: https://plex.home.alborworld.com
          key: {{HOMEPAGE_VAR_PLEX_TOKEN}}
    - Tautulli:
        icon: tautulli.png
#        href: http://tautulli.home.local
        href: https://tautulli.home.alborworld.com
        description: Plex Monitoring
#       For some reason the siteMonitor for Tautulli wants http and not https
#        siteMonitor: https://tautulli.home.alborworld.com
        siteMonitor: http://tautulli.home.local
        widget:
          type: tautulli
#          url: http://tautulli.home.local
          url: https://tautulli.home.alborworld.com
          key: {{HOMEPAGE_VAR_TAUTULLI_API_KEY}}
          enableUser: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: false

- Media:
    - Prowlarr:
        icon: prowlarr.png
#        href: http://prowlarr.home.local
        href: https://prowlarr.home.alborworld.com
        description: Indexer Manager
#        siteMonitor: http://prowlarr.home.local
        siteMonitor: https://prowlarr.home.alborworld.com
        widget:
          type: prowlarr
#          url: http://prowlarr.home.local
          url: https://prowlarr.home.alborworld.com
          key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}
    - Radarr:
        icon: radarr.png
#        href: http://radarr.home.local
        href: https://radarr.home.alborworld.com
        description: Movies Automation
#        siteMonitor: http://radarr.home.local
        siteMonitor: https://radarr.home.alborworld.com
        widget:
          type: radarr
#          url: http://radarr.home.local
          url: https://radarr.home.alborworld.com
          key: {{HOMEPAGE_VAR_RADARR_API_KEY}}
    - Readarr:
        icon: readarr.png
#        href: http://readarr.home.local
        href: https://readarr.home.alborworld.com
        description: Books Automation
#        siteMonitor: http://readarr.home.local
        siteMonitor: https://readarr.home.alborworld.com
        widget:
          type: readarr
#          url: http://readarr.home.local
          url: https://readarr.home.alborworld.com
          key: {{HOMEPAGE_VAR_READARR_API_KEY}}
    - Sonarr:
        icon: sonarr.png
#        href: http://sonarr.home.local
        href: https://sonarr.home.alborworld.com
        description: TV Shows Automation
#        siteMonitor: http://sonarr.home.local
        siteMonitor: https://sonarr.home.alborworld.com
        widget:
          type: sonarr
#          url: http://sonarr.home.local
          url: https://sonarr.home.alborworld.com
          key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
    - Tdarr:
        icon: tdarr.png
#        href: http://tdarr.home.local
        href: https://tdarr.home.alborworld.com
        description: Media Transcoding
#        siteMonitor: http://tdarr.home.local
        siteMonitor: https://tdarr.home.alborworld.com
        widget:
          type: tdarr
#          url: http://tdarr.home.local
          url: https://tdarr.home.alborworld.com

- Utilities:
    - Home Assistant:
        icon: home-assistant.png
#        href: http://homeassistant.home.local
        href: https://homeassistant.home.alborworld.com
        description: Home Automation
#        siteMonitor: http://homeassistant.home.local
        siteMonitor: https://homeassistant.home.alborworld.com
    - NextCloud:
        icon: nextcloud.png
#        href: http://nextcloud.home.local
        href: https://nextcloud.shamanism-nature.com
        description: Personal Cloud Storage
#        siteMonitor: http://nextcloud.home.local
        siteMonitor: https://nextcloud.shamanism-nature.com
    - Syncthing:
        icon: syncthing.png
#        href: http://syncthing.home.local
        href: https://syncthing.home.alborworld.com
        description: File Synchronization
#        siteMonitor: http://syncthing.home.local
        siteMonitor: https://syncthing.home.alborworld.com
    - Synology Photos:
        icon: synology-photos.png
        href: https://alborworld-diskstation.synology.me/?launchApp=SYNO.Foto.AppInstance
        description: Media Gallery

