services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: UptimeKuma
    volumes:
      - ${VOLUMEDIR}/uptime-kuma:/app/data
    labels:
      # TRAEFIK
      - traefik.enable=true
      # Old UptimeKuma router (insecure)
      - traefik.http.routers.uptimekuma-insecure.rule=Host(`uptimekuma.home.local`)
      - traefik.http.routers.uptimekuma-insecure.entrypoints=web
      # UptimeKuma router (secure)
      - traefik.http.routers.uptimekuma.rule=Host(`uptimekuma.${LOCAL_DOMAIN}`)
      - traefik.http.routers.uptimekuma.entrypoints=websecure
      - traefik.http.routers.uptimekuma.tls=true
      - traefik.http.routers.uptimekuma.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Monitoring
      - homepage.name=Uptime Kuma
      - homepage.icon=uptime-kuma.png
      - homepage.href=https://uptimekuma.${LOCAL_DOMAIN}
      - homepage.description=Uptime Monitoring
      - homepage.siteMonitor=https://uptimekuma.${LOCAL_DOMAIN}
      - homepage.widget.type=uptimekuma
      - homepage.widget.url=https://uptimekuma.${LOCAL_DOMAIN}
      - homepage.widget.slug=shamanism
    restart: always