version: "3.9"

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: Syncthing
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/syncthing:/config
      - /volume1/homes/Alessandro/Books:/config/Books
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.syncthing.loadbalancer.server.port=8384
      - traefik.http.routers.syncthing.rule=Host(`syncthing.${LOCAL_DOMAIN}`)
      - traefik.http.routers.syncthing.entrypoints=websecure
      - traefik.http.routers.syncthing.service=syncthing
      - traefik.http.routers.syncthing.tls=true
      - traefik.http.routers.syncthing.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Home & Utilities
      - homepage.name=Syncthing
      - homepage.icon=syncthing.png
      - homepage.href=https://syncthing.${LOCAL_DOMAIN}
      - homepage.description=File Synchronization
      - homepage.siteMonitor=https://syncthing.${LOCAL_DOMAIN}
    restart: unless-stopped
