services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: Overseerr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Amsterdam
    ports:
      - "5055:5055"
    volumes:
      - ${VOLUMEDIR}/overseerr:/config
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.overseerr.loadbalancer.server.port=5055
      # Old Overseerr router (insecure)
      - traefik.http.routers.overseerr-insecure.rule=Host(`overseerr.home.local`)
      - traefik.http.routers.overseerr-insecure.entrypoints=web
      - traefik.http.routers.overseerr-insecure.service=overseerr
      # Overseerr router (secure)
      - traefik.http.routers.overseerr.rule=Host(`overseerr.home.alborworld.com`)
      - traefik.http.routers.overseerr.entrypoints=websecure
      - traefik.http.routers.overseerr.service=overseerr
      - traefik.http.routers.overseerr.tls=true
      - traefik.http.routers.overseerr.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Plex
      - homepage.name=Overseerr
      - homepage.icon=overseerr.png
      - homepage.href=https://overseerr.home.alborworld.com
      - homepage.description=Request Movies and TV Shows
      - homepage.siteMonitor=https://overseerr.home.alborworld.com
      - homepage.widget.type=overseerr
      - homepage.widget.url=https://overseerr.home.alborworld.com
      - homepage.widget.key=${OVERSEERR_API_KEY}
    restart: always
