services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: Overseerr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Amsterdam
    ports:
      - "5055:5055"
    volumes:
      - ${VOLUMEDIR}/overseerr:/config
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.overseerr.loadbalancer.server.port=5055
      - traefik.http.routers.overseerr.rule=Host(`overseerr.${LOCAL_DOMAIN}`)
      - traefik.http.routers.overseerr.entrypoints=websecure
      - traefik.http.routers.overseerr.service=overseerr
      - traefik.http.routers.overseerr.tls=true
      - traefik.http.routers.overseerr.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Media Servers
      - homepage.name=Overseerr
      - homepage.icon=overseerr.png
      - homepage.href=https://overseerr.${LOCAL_DOMAIN}
      - homepage.description=Media Request Management
      - homepage.siteMonitor=https://overseerr.${LOCAL_DOMAIN}
      - homepage.widget.type=overseerr
      - homepage.widget.url=https://overseerr.${LOCAL_DOMAIN}
      - homepage.widget.key=${OVERSEERR_API_KEY}
    restart: always
