services:
  dockerproxy-ds:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: DockerProxy-DS
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.dockerproxy-diskstation.loadbalancer.server.port=2375
      - traefik.http.routers.dockerproxy-diskstation.rule=Host(`dockerproxy.diskstation.${LOCAL_DOMAIN}`)
      - traefik.http.routers.dockerproxy-diskstation.entrypoints=websecure
      - traefik.http.routers.dockerproxy-diskstation.service=dockerproxy-diskstation
      - traefik.http.routers.dockerproxy-diskstation.tls=true
      - traefik.http.routers.dockerproxy-diskstation.tls.certresolver=cloudflare
    restart: unless-stopped
