services:

  oauth2-proxy:
    container_name: OAuth2Proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
#    ports:
#    - 4180:4180
    environment:
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_COOKIE_DOMAINS=.${LOCAL_DOMAIN} # Required so cookie can be read on all subdomains.
      - OAUTH2_PROXY_WHITELIST_DOMAINS=.${LOCAL_DOMAIN} # Required to allow redirection back to original requested target.
      # Configure to use PocketId
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS='*'
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://id.${LOCAL_DOMAIN}
      - OAUTH2_PROXY_REDIRECT_URL=https://oauth2.${LOCAL_DOMAIN}/oauth2/callback
      #
      #- OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST=true
      #- OAUTH2_PROXY_COOKIE_CSRF_EXPIRE=5m
      #- OAUTH2_PROXY_CUSTOM_TEMPLATES_DIR="/templates"
      - OAUTH2_PROXY_REVERSE_PROXY=true
#    volumes:
#      - ${VOLUMEDIR}/oauth2-proxy/templates/:/templates:ro
    depends_on:
      - traefik
      - pocket-id
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.routers.oauth2-proxy.rule=Host(`oauth2.${LOCAL_DOMAIN}`)
      - traefik.http.routers.oauth2-proxy.entrypoints=websecure
      - traefik.http.routers.oauth2-proxy.tls=true
      - traefik.http.routers.oauth2-proxy.tls.certresolver=cloudflare
      - "traefik.http.services.oauth2-proxy.loadbalancer.server.port=4180"
    restart: unless-stopped
