services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: Seerr
    init: true
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "5055:5055"
    depends_on:
      plex:
        condition: service_started
    volumes:
      - ${VOLUMEDIR}/seerr:/app/config
    labels:
      # WATCHTOWER
      - com.centurylinklabs.watchtower=true
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.seerr.loadbalancer.server.port=5055
      - traefik.http.routers.seerr.rule=Host(`seerr.${LOCAL_DOMAIN}`)
      - traefik.http.routers.seerr.entrypoints=websecure
      - traefik.http.routers.seerr.service=seerr
      - traefik.http.routers.seerr.tls=true
      - traefik.http.routers.seerr.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Media Servers
      - homepage.name=Seerr
      - homepage.icon=overseerr.png
      - homepage.href=https://seerr.${LOCAL_DOMAIN}
      - homepage.description=Media Request Management
      - homepage.siteMonitor=https://seerr.${LOCAL_DOMAIN}
      - homepage.widget.type=overseerr
      - homepage.widget.url=https://seerr.${LOCAL_DOMAIN}
      - homepage.widget.key=${SEERR_API_KEY}
    restart: always
