services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: SpeedTestTracker
    ports:
      - 8084:80
      - 8444:443
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - APP_NAME="Speedtest Tracker"
      - APP_KEY=${SPEED_TEST_TRACKER_APP_KEY}
      - FORCE_HTTPS=false
      - DB_CONNECTION=sqlite
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/speedtest-tracker:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"
      # Old SpeetTestTracker router (insecure)
      - "traefik.http.routers.speedtest-insecure.rule=Host(`speedtest.home.local`)"
      - "traefik.http.routers.speedtest-insecure.entrypoints=web" 
      - "traefik.http.routers.speedtest-insecure.service=speedtest"
      # SpeetTestTracker router (secure)
      - "traefik.http.routers.speedtest.rule=Host(`speedtest.home.alborworld.com`)"
      - "traefik.http.routers.speedtest.entrypoints=websecure"
      - "traefik.http.routers.speedtest.service=speedtest"
      - "traefik.http.routers.speedtest.tls=true"
      - "traefik.http.routers.speedtest.tls.certresolver=cloudflare"
    restart: unless-stopped