services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: SpeedTestTracker
    ports:
      - 8084:80
      - 8444:443
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - APP_NAME="Speedtest Tracker"
      - APP_KEY=${SPEED_TEST_TRACKER_APP_KEY}
      - FORCE_HTTPS=false
      - DB_CONNECTION=sqlite
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/speedtest-tracker:/config
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.speedtest.loadbalancer.server.port=80
      # Old Speedtest router (insecure)
      - traefik.http.routers.speedtest-insecure.rule=Host(`speedtest.home.local`)
      - traefik.http.routers.speedtest-insecure.entrypoints=web
      - traefik.http.routers.speedtest-insecure.service=speedtest
      # Speedtest router (secure)
      - traefik.http.routers.speedtest.rule=Host(`speedtest.${LOCAL_DOMAIN}`)
      - traefik.http.routers.speedtest.entrypoints=websecure
      - traefik.http.routers.speedtest.service=speedtest
      - traefik.http.routers.speedtest.tls=true
      - traefik.http.routers.speedtest.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Monitoring
      - homepage.name=SpeedTest Tracker
      - homepage.icon=speedtest-tracker.png
      - homepage.href=https://speedtest.${LOCAL_DOMAIN}
      - homepage.description=Internet Speed Monitoring
      - homepage.siteMonitor=https://speedtest.${LOCAL_DOMAIN}
      - homepage.widget.type=speedtest
      - homepage.widget.url=https://speedtest.${LOCAL_DOMAIN}
      - homepage.widget.version=1
      - homepage.widget.bitratePrecision=3
    restart: unless-stopped