services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: Prowlarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Amsterdam
    volumes:
      - ${VOLUMEDIR}/prowlarr:/config
    network_mode: "service:gluetun"
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${LOCAL_DOMAIN}`)
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.service=prowlarr
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.routers.prowlarr.tls.certresolver=cloudflare
      # HOMEPAGE
      - homepage.group=Media Automation
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=https://prowlarr.${LOCAL_DOMAIN}
      - homepage.description=Indexer Manager
      - homepage.siteMonitor=https://prowlarr.${LOCAL_DOMAIN}
      - homepage.widget.type=prowlarr
      - homepage.widget.url=https://prowlarr.${LOCAL_DOMAIN}
      - homepage.widget.key=${PROWLARR_API_KEY}
    restart: always
