services:
  authelia:
    image: authelia/authelia:latest
    container_name: Authelia
    user: "${UID}:${GID}"
    volumes:
      - ./config/configuration.yml:/config/configuration.yml:ro
      - ${VOLUMEDIR}/authelia/secrets:/config/secrets:ro
      - ${VOLUMEDIR}/authelia/data:/config/data:rw
    environment:
      - TZ=Europe/Amsterdam
      - LOCAL_DOMAIN=${LOCAL_DOMAIN}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET=${AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET}
    command:
      - "authelia"
      - "--config=/config/configuration.yml"
      - "--config.experimental.filters=template"
    ports:
      - "9091:9091"
    labels:
      # TRAEFIK
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`auth.${LOCAL_DOMAIN}`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.tls=true
      - traefik.http.routers.authelia.tls.certresolver=cloudflare
      # ForwardAuth middleware
      - traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://auth.${LOCAL_DOMAIN}
#      - traefik.http.middlewares.authelia.forwardAuth.address:http://authelia:9091/api/authz/forward-auth
      - traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
      # HOMEPAGE
      - homepage.group=Infrastructure
      - homepage.name=Authelia
      - homepage.icon=authelia.png
      - homepage.href=https://auth.${LOCAL_DOMAIN}
      - homepage.siteMonitor=https://auth.${LOCAL_DOMAIN}
      - homepage.description=Authentication Gateway
    restart: unless-stopped
