---
- name: Restart openclaw
  ansible.builtin.systemd:
    name: openclaw
    state: restarted
    daemon_reload: true

- name: Restore iptables
  ansible.builtin.command: iptables-restore < /etc/iptables/rules.v4
  changed_when: true
