services:
  # https://www.reddit.com/r/Traefik/comments/w8v52z/running_traefik_with_multiple_docker_hosts/
  traefik-kop-dh:
    image: "ghcr.io/jittering/traefik-kop:0.19.3"
    container_name: TreaefikKop-DH
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_ADDR=${RASPBERRYPI_IP}:6379
      - BIND_IP=${DOCKERHOST_IP}
      - KOP_HOSTNAME=dockerhost
    labels:
      - wud.watch=false
    restart: always